Controllers/DepartmanController.cs
using ofis_ise.Models.EntityFramework;
using ofis_ise.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ofis_ise.Controllers
{
    [Authorize(Roles = "A,U")]
    public class DepartmanController : Controller
    {
        // GET: Departman
        ofissEntities db = new ofissEntities();
        //[HandleError] proje seviyesine çıkartıldı
        public ActionResult Index()
        {
            var model = db.Departman.ToList();
            return View(model);
        }
        [HttpGet]
        public ActionResult Yeni(string DepartmanAdi)
        {

            return View("DepartmanForm", new Departman());
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Kaydet(Departman departman)
        {
            if (!ModelState.IsValid)
            {
                return View("DepartmanForm");
            }
            MesajViewModel model = new MesajViewModel();
            if (departman.Id == 0)
            {
                db.Departman.Add(departman);
                model.Mesaj = departman.Ad+"başarıyla eklendi..";
            }
            else
            {
                var GuncellenecekDepartman = db.Departman.Find(departman.Id);
                if (GuncellenecekDepartman == null)
                {
                    return HttpNotFound();
                }
                GuncellenecekDepartman.Ad = departman.Ad;
                model.Mesaj = departman.Ad + "başarıyla güncellendi..";
            }
            //db.Departman.Add(departman);
            db.SaveChanges();
            model.Status=true;
            model.LinkText = "Departman listesi";
            model.Url = "/Departman";

            return View("_Mesaj",model);

        }

        public ActionResult Guncelle(int id)
        {
            var model = db.Departman.Find(id);
            if (model == null)
                return HttpNotFound();
            return View("DepartmanForm", model);
        }
        public ActionResult Sil(int id)
        {
            var SilinecekDepartman = db.Departman.Find(id);
            if (SilinecekDepartman == null)
                return HttpNotFound();
            db.Departman.Remove(SilinecekDepartman);
            //Entity validation hata tesbiti
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/PersonelController.cs
using ofis_ise.Models.EntityFramework;
using ofis_ise.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ofis_ise.Controllers
{
    [Authorize(Roles = "A,U")]
    public class PersonelController : Controller
    {
        // GET: Personel

        ofissEntities db = new ofissEntities();
        public ActionResult Index()
        {
            var model = db.Personel.Include(x => x.Departman).ToList();
            return View(model);
        }
       

        public ActionResult Yeni()

        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = new Personel()
            };


            return View("PersonelForm", model);
        }
        //[ValidateAntiForgeryToken]
        public ActionResult Kaydet(Personel personel)
        {
            if (!ModelState.IsValid)
            {
                var model = new PersonelFormViewModel()
                {
                    Departmanlar = db.Departman.ToList(),
                    Personel = personel
                };
                return View("PersonelForm", model);
            }
            if (personel.Id == 0) //ekleme işlemi
            {
                db.Personel.Add(personel);
            }
            else //Guncelle
            {
                db.Entry(personel).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Guncelle(int id)
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = db.Personel.Find(id)
            };

            return View("PersonelForm", model);
        }
        public ActionResult Sil(int id)
        {
            var SilinecekPersonel = db.Personel.Find(id);
            if (SilinecekPersonel == null)
            {
                return HttpNotFound();
            }
            db.Personel.Remove(SilinecekPersonel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelleriListele(int id)
        {
            var model = db.Personel.Where(x => x.DepartmanId == id).ToList();
            return PartialView(model);
        }
        public ActionResult ToplamMaas()
        {
            ViewBag.Maas = db.Personel.Sum(x=>x.Mass);
            return PartialView();
        }
    }
}

Views/Departman/DepartmanForm.cshtml
@model ofis_ise.Models.EntityFramework.Departman
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Yeni</h2>
<link href="~/Content/bootstrap.css" rel="stylesheet" />

@*@<form method="post">
        <div class="form-group">
            <label>Departman Adı</label>
            <input type="text"name="Ad" class="form-control" />

        </div>
        <button type="submit" class="btn btn-success">Ekle</button>
    </form>*@
<div id="mesaj"></div>
@using (Ajax.BeginForm("Kaydet", "Departman", new AjaxOptions {HttpMethod="POST", UpdateTargetId="mesaj" }))
{
    @*@Html.AntiForgeryToken()*@
    <div class="form-group">

        @Html.LabelFor(m => m.Ad)
        @Html.TextBoxFor(m => m.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Ad)
        @*kullanıcıya hata mesajı eklendi*@
    </div>
    @Html.HiddenFor(m => m.Id)
    <button type="submit" class="btn btn-success">Kaydet</button>
}
@section scripts
    {
   
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    }

Views/Departman/Index.cshtml
@using ofis_ise.Models.EntityFramework
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Departman Listesi</h2>

<a class="btn btn-success" href="/Departman/Yeni">Yeni Departman</a>

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<table class="table table-bordered" id="tblDepartmanlar">
    <thead class="thead-dark">
        <tr>
            <th>ID</th>
            <th>Ad</th>
            <th>Güncelle</th>
            <th>Sil</th>
            <th>Personeller</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var departman in Model)
        {
            <tr>
                <td>@departman.Id</td>
                <td>@departman.Ad</td>
                <td><a class="btn btn-primary" href="/Departman/Guncelle/@departman.Id">Güncelle</a></td>
                <td><a class="btn btn-warning" href="/Departman/Sil/@departman.Id">Sil</a></td>
                @**<td>@Html.ActionLink("Personelleri Göster","PersonelleriListele","Personel",new {id=departman.Id},new {@class="btn btn-primary" })</td>*@
                <td>@Ajax.ActionLink("Personelleri Göster","PersonelleriListele","Personel",new {id=departman.Id},new AjaxOptions {HttpMethod="GET",UpdateTargetId="personelListesi" },
                   new { @class = "btn btn-primary" })</td>
            </tr>

        }

    </tbody>
</table>
<div id="personelListesi"></div>